spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpd_entire?useSSL=false&serverTimezone=UTC
    username: root
    password: 123qwe
    #springboot2之后，mysql驱动是com.mysql.cj.jdbc.Driver
    driver-Class-Name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  redis:
    host: 127.0.0.1


  http:
    encoding:
      charset: utf-8
      enabled: true
#打印匹配报告
debug: true